apiVersion: v1
kind: Secret
metadata:
  name: multimodal-rag-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
